POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthdGVyeW5hSyIsImlkIjoiNWY4ZDY2OTc5ZjYwOGExZTM3NTBlMTQ3IiwiaWF0IjoxNjAzNTU5MTgwfQ.LS1fbhCbcxNbLAtNBXzikmW3cfvZ67ji-uTSp_4NzFP
    
{
    "title" : "MiddlewareToken",
    "author" : "MT",
    "url" : "www.blogM.com"
}